### ISSUE TITLE
Beam: consider switching to decline for cli arguments

### ISSUE THREAD

**Issue by chuwy** [snowplow/enrich#266]

**Comment by chuwy** [comment]
Migrated from https://github.com/snowplow/beam-enrich/issues/17 (comments are auto-generated)

**Comment by chuwy** [comment]
We were thinking that absence of `--arg=value` syntax in decline is a blocker for this ticket, but apparently as pointed out in https://github.com/bkirwi/decline/issues/195 that syntax is already supported, so we can try that out.

**Comment by benjben** [comment]
Beam Enrich got deprecated in https://github.com/snowplow/enrich/commit/6e0a56ab8ee979cae124b1d20b20cd65e90ac0a2
