### ISSUE TITLE
Beam: split `EnrichWithLocalFileSpec` test into two

### ISSUE THREAD

**Issue by chuwy** [snowplow/enrich#270]
This test currently tests two things at the same time:

- that we can successfully download and use the latest version of the Maxmind DB for IP lookups from the `hosted-assets` bucket;
- that the enrichment produces the expected output.

However, when a new version of the DB is uploaded to `hosted-assets`, this test can start failing because the data points associated with the hardcoded IP address in it might have changed.

It will be better to split this into two tests. One will test the download works as expected. The other one will use the same DB file every time, eliminating the need to re-write the test every so often.

Moved from: https://github.com/snowplow/snowplow/issues/4130

**Comment by chuwy** [comment]
Migrated from https://github.com/snowplow/beam-enrich/issues/23 (comments are auto-generated)

**Comment by benjben** [comment]
Beam Enrich got deprecated in https://github.com/snowplow/enrich/commit/6e0a56ab8ee979cae124b1d20b20cd65e90ac0a2
