### ISSUE TITLE
Beam: offset step names

### ISSUE THREAD

**Issue by chuwy** [snowplow/enrich#272]
`withName` applies to the next step not the preceding one.

Moved from: https://github.com/snowplow/snowplow/issues/3944

**Comment by chuwy** [comment]
Migrated from https://github.com/snowplow/beam-enrich/issues/25 (comments are auto-generated)

**Comment by chuwy** [comment]
Descheduling. To me current node names make perfect sense.

**Comment by benjben** [comment]
Beam Enrich got deprecated in https://github.com/snowplow/enrich/commit/6e0a56ab8ee979cae124b1d20b20cd65e90ac0a2
