### ISSUE TITLE
Beam: customize user agent

### ISSUE THREAD

**Issue by chuwy** [snowplow/enrich#273]
currently impossible, sister ticket to snowplow-incubator/snowplow-google-cloud-storage-loader#10

Moved from: https://github.com/snowplow/snowplow/issues/3931

**Comment by chuwy** [comment]
Migrated from https://github.com/snowplow/beam-enrich/issues/26 (comments are auto-generated)

**Comment by benjben** [comment]
Beam Enrich got deprecated in https://github.com/snowplow/enrich/commit/6e0a56ab8ee979cae124b1d20b20cd65e90ac0a2
