### ISSUE TITLE
Beam: volume mount permissions in containers

### ISSUE THREAD

**Issue by chuwy** [snowplow/enrich#274]
Currently Snowplow containers run as snowplow user. 

When mounting a volume, it gets mounted as root, this makes impossible to access files from the program that is running as snowplow user.

The use case for this was on a gcp container, we tried to pass the service account file to the container using a volume, so the program running there could do the authentication and connect to gcp.

Example: 
```
docker run --rm -v /root:/cfg -e GOOGLE_APPLICATION_CREDENTIALS='/cfg/sp-loader.json' snowplow-docker-registry.bintray.io/snowplow/snowplow-bigquery-mutator:0.1.0-rc13 listen --resolver=$RESOLVER --config=$CONFIG --verbose
```

This seems to be an old issue yet to have a proper solution https://github.com/moby/moby/issues/2259

Moved from: https://github.com/snowplow/snowplow/issues/3896

**Comment by chuwy** [comment]
Migrated from https://github.com/snowplow/beam-enrich/issues/27 (comments are auto-generated)

**Comment by chuwy** [comment]
Hey @oguzhanunlu! Are we going to deal with this in 1.3.0?

**Comment by oguzhanunlu** [comment]
I missed the notification somehow, sorry @chuwy , I don't think we'll include it in 1.3.0

**Comment by benjben** [comment]
Beam Enrich got deprecated in https://github.com/snowplow/enrich/commit/6e0a56ab8ee979cae124b1d20b20cd65e90ac0a2
