### ISSUE TITLE
Beam: retrieve configuration from Google Cloud Datastore

### ISSUE THREAD

**Issue by chuwy** [snowplow/enrich#275]
Moved from: https://github.com/snowplow/snowplow/issues/3738

**Comment by chuwy** [comment]
Migrated from https://github.com/snowplow/beam-enrich/issues/28 (comments are auto-generated)

**Comment by benjben** [comment]
Beam Enrich got deprecated in https://github.com/snowplow/enrich/commit/6e0a56ab8ee979cae124b1d20b20cd65e90ac0a2
