### ISSUE TITLE
Add possibility to use STS to authenticate

### ISSUE THREAD

**Issue by benjben** [snowplow/enrich#318]
In order to be able to use [AWS Security Token Service](https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html) to authenticate.

For example it can be used to pass AWS credentials with AWS_PROFILE environment variable.

Related to https://github.com/snowplow/snowplow/pull/4372

**Comment by Lincon-Freitas** [comment]
Would be perfect to have the AssumeRoleWithWebIdentity available to allow me assuming roles directly in my pods.
