### ISSUE TITLE
Common: convert null fields in EnrichedEvent to None in PartiallyEnrichedEvent

### ISSUE THREAD

**Issue by istreeter** [snowplow/enrich#331]
This concerns the method [toPartiallyEnrichedEvent](https://github.com/snowplow/enrich/blob/stream_enrich/1.1.0/modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/outputs/EnrichedEvent.scala#L252)

Currently, if an integer field is null, then it gets converted to `Some(0)` in the partially enriched event.  Similarly for optional booleans and optional floats.

**Comment by benjben** [comment]
BTW I wonder if `PartiallyEnrichedEvent` adds value
