### ISSUE TITLE
Stream FS2: add message attributes to PubSub

### ISSUE THREAD

**Issue by miike** [snowplow/enrich#340]
**Project**: Beam Enrich

**Version**: N/A

**Expected behavior**: Message are published with some attributes (e.g., app_id, event_name)

**Actual behavior**: N/A

It's possible to publish messages with high level attributes such as app_id and event_name to the enriched events themselves. This would add the ability for downstream subscribers to filter events making it easier to selectively subscribe to events or for multitenancy applications (e.g., sinking app_ids to different BQ datasets / tables).

**Comment by chuwy** [comment]
I like the idea, @miike. Any downsides that you see apart from increased message size? Do you think it should be configurable?

**Comment by miike** [comment]
Other than the slight increase in message size I can't think of any other downsides. There's some quotas on the number and size of keys / values that can be set but they are reasonably large limits.

User configurable makes some sense - I think an array of keys makes sense with the intent that they would fallback to an empty string (or perhaps some other default?) in the event they are NULL. I'm not sure if we should allow just the core event fields or expand this to include any schemas included in the event as well (which might incur a little bit more processing overhead in retrieving and casting the property to a string).

**Comment by chuwy** [comment]
Going to implement it in next release of FS2 Enrich (it's super easy there to add and it still has an experimental status).

> I think an array of keys makes sense with the intent that they would fallback to an empty string (or perhaps some other default?)

Everywhere in type system, attributes are just `Map[String, String]`. Do you think we can just not adding a key if value is `null`, @miike?

**Comment by miike** [comment]
If null I think that's fine - with the exception of some fields referenced which might come through as null but we might want to attach, e.g., if an event is sent through with no `app_id` we might want to attach `app_id = ''` rather than no app_id (in which case a downstream consumer reliant on the app_id message attribute may not gracefully fail).

**Comment by miike** [comment]
@istreeter You're a champion - this looks great.

**Comment by miike** [comment]
Question on this functionality - can / should this support event properties?

First class fields are quite useful but being able to filter on contexts / events is equally useful (though more technically difficult).

Example use case might be filtering to non-bot traffic on a PubSub attribute using the IAB context.

**Comment by chuwy** [comment]
Hey @miike! I don't think we can support contexts on this iteration, but you're making a very good use case - previously we ruled out contexts / events as a niche use case.

I think we need to come up with a configuration compatible with both "canonical" properties and JSON. I think we can start with what we have in [API/SQL enrichments configs](https://github.com/snowplow/enrich/blob/master/config/enrichments/api_request_enrichment_config.json#L11-L24) and either use the format as is or improve it a bit, for example
* Replace "pojo" with [`atomic`](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/atomic/jsonschema/1-0-0) schema
* Replace JSONPath with JSONPointer (much simpler to implement, much easier and we don't need power of JSONPath - i.e. only scalar values should be "extractable")
* Somehting else?

**Comment by miike** [comment]
Agreed - I don't think it needs to be in the first release as just this functionality goes a long way.

JSON pointers seems like a good way to do this - I imagine most of the time we aren't going to need to traverse anything beyond a top level property or potentially the first element in an array (in the case of contexts) but being able to support this I think is a nice addition. Agreed on the standardisation component as well.

**Comment by istreeter** [comment]
> If null I think that's fine - with the exception of some fields referenced which might come through as null but we might want to attach, e.g., if an event is sent through with no `app_id` we might want to attach `app_id = ''` rather than no app_id (in which case a downstream consumer reliant on the app_id message attribute may not gracefully fail).

In the current implementation, if an event is missing `app_id` then we omit it from the attributes.  We do not attach `app_id = ''`.  And I think this is semantically correct 🤔

[Here is a link to the PubSub filtering documentation](https://cloud.google.com/pubsub/docs/filtering#filtering_syntax).

A downstream consumer could user a filters like:

- `attributes:app_id` to select enriched events that have an app_id (e.g. for if the downstream consumer is reliant on this field)
- `attributes:app_id = "myapp"` to select events from "myapp"
- `attributes:app_id != "myapp"` to select the union of events with missing app_id, and events from all other applications

**Comment by miike** [comment]
> > If null I think that's fine - with the exception of some fields referenced which might come through as null but we might want to attach, e.g., if an event is sent through with no `app_id` we might want to attach `app_id = ''` rather than no app_id (in which case a downstream consumer reliant on the app_id message attribute may not gracefully fail).
> 
> In the current implementation, if an event is missing `app_id` then we omit it from the attributes. We do not attach `app_id = ''`. And I think this is semantically correct 🤔
> 
> [Here is a link to the PubSub filtering documentation](https://cloud.google.com/pubsub/docs/filtering#filtering_syntax).
> 
> A downstream consumer could user a filters like:
> 
> * `attributes:app_id` to select enriched events that have an app_id (e.g. for if the downstream consumer is reliant on this field)
> * `attributes:app_id = "myapp"` to select events from "myapp"
> * `attributes:app_id != "myapp"` to select the union of events with missing app_id, and events from all other applications

I think it's generally pretty unusual to not have an app_id so having the attribute absent (if it's null) seems like a predictable behaviour.
