### ISSUE TITLE
Common: fix PII enrichment adding empty objects instead of missing properties

### ISSUE THREAD

**Issue by chuwy** [snowplow/enrich#351]
If we specify JSONPath like `$.['a', 'b']` and proocess JSON that miss at least one of those properties, the another one will be replaced with an empty object, e.g.

```json
{"a": 1}
```

on input, and

```json
{"a": 1, "b": {}}
```

on output.

This can break downstream consumers as `b` is supposed to be non-object.

It seems to be regression since R117, but cannot see the reason yet, no major changes has been made in PII enrichment and JSONPath lib remained on the same 2.4.0 version.

It seems we just re-introduced https://github.com/snowplow/snowplow/issues/3636 during R118 refactoring.

**Comment by benjben** [comment]
It happened when we replaced `json4s` with `circe` : https://github.com/snowplow/enrich/commit/4d0b947badeec8e1f9f98740dfa963ccb841a596#diff-991a6b97fb9371add7ff0ace34b8c91fR298-R300
