### ISSUE TITLE
Common: replace deprecated constructors in EnrichedEventSpec

### ISSUE THREAD

**Issue by benjben** [snowplow/enrich#354]
Since Java 9 constructors like `new JInteger(0)` are deprecated and constructors like `JInteger.valueOf(0)` need to be used instead.

Marked as a bug as with `-Xfatal-warnings` compilation fails.

**Comment by chuwy** [comment]
Seems it was introduced in https://github.com/snowplow/enrich/issues/331. Before that I clearly remember compiling it on JDK11 after we did https://github.com/snowplow/enrich/issues/252

**Comment by benjben** [comment]
Ah yes ! Ian is probably using JDK 8
