### ISSUE TITLE
Common: disable formatting on compile

### ISSUE THREAD

**Issue by chuwy** [snowplow/enrich#358]
This is [recommended practice](https://scalameta.org/scalafmt/docs/installation.html#format-on-compile) to check formatting as a CI/CD steps.

Any objections @benjben, @oguzhanunlu? Going to remove it from branch if you have any.

**Comment by oguzhanunlu** [comment]
I don't have any objections as long as we make sure unformatted code doesn't get merged

**Comment by oguzhanunlu** [comment]
That's great @chuwy , I'm in then

**Comment by benjben** [comment]
I'm in too !
