### ISSUE TITLE
Common: bump sbt to 1.5.1

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/enrich#366]
sbt 1.4.0 is available and [CHANGELOG](https://github.com/sbt/sbt/releases/tag/v1.4.0) seems appealing
- Build server protocol (BSP) support
- sbtn: a native thin client for sbt -- run sbt as daemon to avoid JVM spinup and loading time 
- build linting
- conditional tasks
- `sbt-dependency-graph` is in-sourced

**Comment by chuwy** [comment]
sbt is not an acronym https://twitter.com/eed3si9n/status/1278358340775686144
