### ISSUE TITLE
Common: fix API Request Enrichment output deserialization

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/enrich#374]
`io.circe.jackson.mapper` deserializes all integers and numbers to `JsonBigDecimal` and downstream in the codebase, it is converted to `DecimalNode` by `circeToJackson()` in `iglu-scala-client`, and the validator treats `DecimalNode` as `number` which results in a bad row with `number found, integer expected` error message in case output schema of API Request Enrichment contains `integer` property

We'll introduce a custom mapper whose only difference compared to the original mapper is how integers are deserialized. Unlike the original, it'll deserialize integers to `JsonLong`.

Note that json schemas might contain integer values that don't fit into `Long` and this case will also result in a bad row, but we don't expect to see this case in real life.

The actual [diff](https://github.com/snowplow/enrich/pull/375/commits/606e074e0b971f788bf709573bb9fdf50a2ae1d0#diff-52c2ad6b30f0646aeac2fc5bf250fd6ed3a4ffc5e9c3accea22f9557b7b6e9dfL35-R33) happens in `CirceJsonDeserializer.deserialize` where

```scala
case JsonTokenId.ID_NUMBER_INT | JsonTokenId.ID_NUMBER_FLOAT =>
  (Some(Json.JNumber(JsonBigDecimal(jp.getDecimalValue))), parserContext)
```

is replaced by

```scala
case JsonTokenId.ID_NUMBER_INT => (Some(Json.JNumber(JsonLong(jp.getLongValue))), parserContext)
case JsonTokenId.ID_NUMBER_FLOAT => (Some(Json.JNumber(JsonBigDecimal(jp.getDecimalValue))), parserContext)
```

**Comment by chuwy** [comment]
Bug manifests itself as an invaildation of a schema, added by API Request enrichment. If output schema requires integer type, the validator complains that "42 is a number, but integer expected", because in its internal representation, 42 is a number.

**Comment by chuwy** [comment]
What about SQL Query enrichment, @oguzhanunlu? It's inputs also seem to be affected, but I don't see any changes regarding to that.
