### ISSUE TITLE
Beam: fix authentication of docker image

### ISSUE THREAD

**Issue by simplylizz** [snowplow/enrich#390]
**Project**: Beam Enrich

**Version**:
* 1.2.3 - works well;
* 1.3.0 - complains, but works;
* 1.4.0 and 1.4.1-rc3 - aren't working at all;

I'm passing a key to Docker in the following way:
```
    -v $HOME/.config/gcloud/application_default_credentials.json:/application_default_credentials.json
    -e GOOGLE_APPLICATION_CREDENTIALS=/application_default_credentials.json
```

And it works fine for bq-loader and enricher 1.2.3, but fails for enricher 1.4.0 and 1.4.1-rc3 (for 1.3.0 - it spews a similar error once and then starts updating pipeline).

Output (1.4.0):
```
WARNING: Could not setup log file in /.config/gcloud/logs, (Error: Could not create directory [/.config/gcloud/logs/2020.11.02]: Permission denied.

Please verify that you have permissions to write to the parent directory.)
ERROR: (gcloud.auth.activate-service-account) The .json key file is not in a valid format.
ERROR: (gsutil) Failed to create the default configuration. Ensure your have the correct permissions on: [/.config/gcloud/configurations].
  Could not create directory [/.config/gcloud/configurations]: Permission denied.

Please verify that you have permissions to write to the parent directory.
Bucket gs://<...>/enrich-dataflow does not exist. Retry: 0/5
ERROR: (gsutil) Failed to create the default configuration. Ensure your have the correct permissions on: [/.config/gcloud/configurations].
  Could not create directory [/.config/gcloud/configurations]: Permission denied.
```

Or this, if I run it as root:
```
ERROR: (gcloud.auth.activate-service-account) The .json key file is not in a valid format.
ServiceException: 401 Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.
Bucket gs://<...>/enrich-dataflow does not exist. Retry: 0/5
```

Output (1.3.0):
```
ERROR: (gcloud.auth.activate-service-account) Unable to read file [/snowplow/config/credentials.json]: [Errno 2] No such file or directory: '/snowplow/config/credentials.json'
ServiceException: 401 Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.
Bucket gs://cw-dev-data-0001-snowplow-tmp/enrich-dataflow exists. Proceeding.
[main] WARN com.networknt.schema.JsonMetaSchema - Unknown keyword exclusiveMinimum - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
[main] WARN com.spotify.scio.VersionUtil$ -
 > A newer version of Scio is available: 0.9.2 -> v0.9.5
 > Use `-Dscio.ignoreVersionWarning=true` to disable this check.
<...>
```

Putting key to `/snowplow/config/credentials.json` doesn't help.

**Steps to reproduce**:

Run something like this:
```
docker run --rm \
    -v /Users/cw2811/repos/cw-snowplow/enrichments:/snowplow/config/enrichments \
    -v /Users/cw2811/repos/cw-snowplow/iglu_resolver.json:/snowplow/config/iglu_resolver.json \
    -v /Users/cw2811/.config/gcloud/application_default_credentials.json:/application_default_credentials.json \
    -e GOOGLE_APPLICATION_CREDENTIALS=/application_default_credentials.json \
    -u root snowplow/beam-enrich:1.4.0 \
    --runner=DataFlowRunner \
    --job-name=snowplow-enrich \
    --update=true \
    --project=<...> \
    --numWorkers=1 \
    --maxNumWorkers=1 \
    --usePublicIps=false \
    --network=<...> \
    --subnetwork=<...> \
    --workerMachineType=n1-standard-1 \
    --diskSizeGb=30 \
    --region=europe-west4 \
    --streaming=true \
    --gcpTempLocation=<...> \
    --raw=<...> \
    --enriched=<...> \
    --bad=<...> \
    --pii=<...> \
    --resolver=/snowplow/config/iglu_resolver.json \
    --enrichments=/snowplow/config/enrichments/
```

**Comment by oguzhanunlu** [comment]
Thanks for the report @simplylizz ! I just reproduced the case and we'll include the fix in the upcoming 1.5.0 release!

**Comment by oguzhanunlu** [comment]
Hey @simplylizz , until we fix this, you can use [`--serviceAccount`](https://cloud.google.com/dataflow/docs/concepts/security-and-permissions#specifying_a_user-managed_controller_service_account) flag to use Beam Enrich docker images.

**Comment by philipherrmann** [comment]
This one also affects running the image snowplow/beam-enrich inside GCP, right? You haven't had to provide service account credentials in 1.2.3 (falling back to the default service account) and get the error message with 1.4.* if you don't. Or would you like to consider/track that as new issue (@oguzhanunlu)?

**Comment by oguzhanunlu** [comment]
> This one also affects running the image snowplow/beam-enrich inside GCP, right?

this is already about running beam-enrich in GCP, do you refer to another service or beam runner? @philipherrmann

**Comment by philipherrmann** [comment]
I meant the following: If you run the docker container that starts up beam enrich with the DataFlowRunner inside GCP, for example lets assume you run the container in GKE, you could allow to fall back to the default service account of GKE. In this case you don't have to provide GOOGLE_APPLICATION_CREDENTIALS nor --serviceAccount for the docker image snowplow/beam-enrich:1.2.3, but you have to for 1.4.*.

Might still be I didn't get it right, and this is also the scenario you were talking about already? Wasn't the original scenario about running `docker run` locally?

**Comment by oguzhanunlu** [comment]
Thanks for the details, I see.

> and this is also the scenario you were talking about already?

It's been some time since I reproduced but I think it is the same scenario so no need for a new ticket
