### ISSUE TITLE
Error: java.io.FileNotFoundException: ./ip_geo (Permission denied)

### ISSUE THREAD

**Issue by ggregoire** [snowplow/enrich#407]
**Project**:  Stream Enrich

**Version**: 1.4.2, 1.4.1, 1.4.0, 1.3.2

**Steps to reproduce**:

I'm running the following Dockerfile on AWS ElasticBeanstalk Docker:

```Dockerfile
FROM snowplow/stream-enrich-kinesis:1.4.2

WORKDIR /app

COPY config.hocon .
COPY resolver.json .
COPY enrichments/ enrichments/

EXPOSE 8000

CMD ["--config", "config.hocon", "--resolver", "file:resolver.json", "--enrichments", "file:enrichments"]
```

With the following ip-lookups config file located in `enrichments/`:

```json
{
	"schema": "iglu:com.snowplowanalytics.snowplow/ip_lookups/jsonschema/2-0-0",
	"data": {
		"name": "ip_lookups",
		"vendor": "com.snowplowanalytics.snowplow",
		"enabled": true,
		"parameters": {
			"geo": {
				"database": "GeoLite2-City.mmdb",
				"uri": "http://snowplow-hosted-assets.s3.amazonaws.com/third-party/maxmind"
			}
		}
	}
}
```

Which gives me the following error:

```
Exception in thread "Thread-4" java.io.FileNotFoundException: ./ip_geo (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at scala.sys.process.ProcessBuilderImpl$FileOutput$$anonfun$$lessinit$greater$3.apply(ProcessBuilderImpl.scala:37)
	at scala.sys.process.ProcessBuilderImpl$FileOutput$$anonfun$$lessinit$greater$3.apply(ProcessBuilderImpl.scala:37)
	at scala.sys.process.ProcessBuilderImpl$OStreamBuilder$$anonfun$$lessinit$greater$4.apply(ProcessBuilderImpl.scala:42)
	at scala.sys.process.ProcessBuilderImpl$OStreamBuilder$$anonfun$$lessinit$greater$4.apply(ProcessBuilderImpl.scala:42)
	at scala.sys.process.ProcessBuilderImpl$ThreadBuilder.go$1(ProcessBuilderImpl.scala:63)
	at scala.sys.process.ProcessBuilderImpl$ThreadBuilder.$anonfun$run$1(ProcessBuilderImpl.scala:67)
	at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:27)
```

I found [the exact same issue](https://github.com/snowplow/snowplow-docker/issues/29) which has been resolved and closed in 2017 but it doesn't help much:

> This is most likely due to the snowplow user not having the right perms, thanks for the report 👍
> We'll fix this in the upcoming release 2.

Or do I have to give `snowplow` user the permission on that file somehow in my own Dockerfile?

**Comment by ggregoire** [comment]
Anyone got an idea?

I also wanted to try to run the jar instead of the docker image since it might be a problem with the image *snowplow/stream-enrich-kinesis* itself (according to the issue from 2017), but the jar isn't available (https://github.com/snowplow/enrich/issues/406).

**Comment by ggregoire** [comment]
Got it working by build and running the jar instead of using the docker image.

```
FROM mozilla/sbt

RUN apt-get update && apt-get install -y --no-install-recommends \
  ca-certificates \
  git

WORKDIR /app

RUN git config --global http.sslCAinfo /etc/ssl/certs/ca-certificates.crt \
  && git clone https://github.com/snowplow/enrich.git

WORKDIR /app/enrich

RUN sbt "project kinesis" assembly \
  && cp modules/kinesis/target/scala-2.12/snowplow-stream-enrich-kinesis-1.4.2.jar /app/snowplow-stream-enrich-kinesis-1.4.2.jar

WORKDIR /app

COPY config.hocon .
COPY resolver.json .
COPY enrichments/ enrichments/

EXPOSE 8000

CMD ["java", "-jar", "snowplow-stream-enrich-kinesis-1.4.2.jar", "--config", "config.hocon", "--resolver", "file:resolver.json", "--enrichments", "file:enrichments"]
```

Still interested in using the docker image if anyone knows how I could avoid the "Permission denied" error.

**Comment by benjben** [comment]
Hi @ggregoire ,

The issue that you're facing is probably that enrich [is running with](https://github.com/snowplow/enrich/blob/master/project/BuildSettings.scala#L127) `snowplow` user but the directories that you're creating in your Dockerfile are not with this user. You could `chmod 777` them but still, you don't need to create a new Docker image wrapping enrich image, you can run directly enrich image with something like :

```
docker run \
      -d \
      --name ${app_name} \
      --restart always \
      --log-driver awslogs \
      --log-opt awslogs-group=${log_group_name} \
      --log-opt awslogs-stream=`ec2metadata --instance-id` \
      --network host \
      -v $${config_dir}:/snowplow/config \
      -e 'JAVA_OPTS=-Xms${heap_size} -Xmx${heap_size} -Dorg.slf4j.simpleLogger.defaultLogLevel=${log_level}' \
      snowplow/stream-enrich-kinesis:${app_version} \
      --config /snowplow/config/${config_path} \
      --resolver ${resolver} \
      --enrichments ${enrichments} \
      --force-cached-files-download
```

Closing the issue as there is nothing wrong with enrich.

**Comment by chuwy** [comment]
If you're still facing an issue, @ggregoire - please  feel free to reach out our [discourse forums](discourse.snowplowanalytics.com/) - you'll get help there much quicker as we use github for bug tracking and feature requests only.
