### ISSUE TITLE
Stream: fix incorrect event construction for heartbeat events

### ISSUE THREAD

**Issue by miike** [snowplow/enrich#410]
**Project**: Kinesis Enrich

**Version**: all

**Expected behavior**: Should emit heartbeat events that validate against the `com.snowplowanalytics.monitoring.kinesis/app_heartbeat/jsonschema/1-0-0` schema.

**Actual behavior**: Events are not valid due to a spelling error for the "interval" property.

**Comment by chuwy** [comment]
Nice catch!
