### ISSUE TITLE
Common: bump commons-codec to 1.15

### ISSUE THREAD

**Issue by istreeter** [snowplow/enrich#430]
A unit test in conversionUtilsSpec failed on a randomly generated string generated by scalacheck:

```
Error:    x decodeBase64Url should not return failure on any other string
Error:   Falsified after 70 passed tests.
Error:   > ARG_0: "3u"
Error:   > ARG_0_ORIGINAL: "鸯鋗隖ᣰኢ㮈◳3ꇞ著檐亅윍㏐锰鐚묻䷰㒾哫蠵盜嚛඼嚪䷤隊ኼਸ흂㗙㬍漰⸷ﴎ쨗櫤憠껖낧uႇ↳㠤鸽、ꑶ༓Ʉ髴㨯漩躶"
Error:   The seed is pwY8zvcMyQEEqruPZQJpw0ju_x9ZUYzRi9xnRifCu3L=
Error:   
Error:   > Left(could not base64 decode: Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possible value) is not Right (conversionUtilsSpecs.scala:220)
```

It is probably related to [this explanation](https://issues.apache.org/jira/browse/CODEC-263?focusedCommentId=16981194&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16981194) in Apache's jira.  Behaviour changed in version 1.13 of the codec.

**Comment by istreeter** [comment]
This can be fixed by bumping to commons-codec v1.15.  There was a bug which is [described here](https://issues.apache.org/jira/browse/CODEC-270) and which was fixed in [version 1.14](https://github.com/apache/commons-codec/blob/c89d2af770f05457fbefa5fb4713c888bf177fb2/RELEASE-NOTES.txt#L69)

**Comment by chuwy** [comment]
Did you consider switching to `java.util.Base64`?

**Comment by istreeter** [comment]
I agree `java.util.Base64` should also work, but here I made the minimum change possible to get something that works.  Note that `commons-codec` is pulled into our assembly anyway, via some of our other dependencies.

There is a difference between the implementations.  For example, whether an exception is raised on a url-unsafe character

```scala
scala> java.util.Base64.getUrlDecoder.decode("+")
java.lang.IllegalArgumentException: Input byte[] should at least have 2 bytes for base64 bytes
  at java.base/java.util.Base64$Decoder.outLength(Base64.java:668)
  at java.base/java.util.Base64$Decoder.decode(Base64.java:534)
  at java.base/java.util.Base64$Decoder.decode(Base64.java:558)
  ... 36 elided

scala> new org.apache.commons.codec.binary.Base64(true).decode("+")
res10: Array[Byte] = Array()
```

**Comment by chuwy** [comment]
My reasoning was mostly based on a poor record of backward-compatibility in commons-codec (https://github.com/snowplow/snowplow/issues/3601 for example), I usually afraid to touch the lib.
