### ISSUE TITLE
Documentation for using DynamoDB for Configuring Stream Enrich

### ISSUE THREAD

**Issue by bostrowski13** [snowplow/enrich#472]
**Project**: Stream Enrich

**Version**: 2.0.1

**Expected behavior**:
There seems to be little documentation and no examples for configuration of using DyanmoDB to store and retrivee configs for resolver.json and enrichments.  
While the following provides items on service startup, theres no examples of how that data should be stored in DynamoDB.
https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/enrichment-components/stream-enrich/run-stream-enrich/#2-config-in-dynamodb-datastore

Is there a desired format?  or is this just 1 blob for the value as follows?

```Terraform
resource "aws_dynamodb_table_item" "resolver_json" {
  depends_on = ["data.template_file.resolver_json_tpl"]
  table_name = aws_dynamodb_table.sp_enricher_config_table.id
  hash_key   = var.sp_dynamodb_cw_table_hash_key
  item       = <<ITEM
{
  "resolver": {"S": "${data.template_file.resolver_json_tpl.rendered}"}
}
ITEM
}
```

where "data.template_file.resolver_json_tpl.rendered" is just a standard resolver.json file which we insert the iglu server name into.

```
{
  "schema": "iglu:com.snowplowanalytics.iglu/resolver-config/jsonschema/1-0-3",
  "data": {
    "cacheSize": 500,
    "repositories": [
      {
          "name": "Iglu repository",
          "priority": 0,
          "vendorPrefixes": [ "com.snowplowanalytics" , "com.company.my"],
          "connection": {
            "http": {
              "uri": "${iglu_server}"
            }
          }
      }
    ]
  }
}
```

**Actual behavior**:
Provide example and more robust documentation for use of DynamoDB.

Also, I would've used the forum, however I'm not able to register because I can't click to send the confiramtion email.

**Comment by benjben** [comment]
Hi @bostrowski13 ,

You're right that the documentation could have been more clear.

We added some details : https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/enrichment-components/stream-enrich/run-stream-enrich/#2-1-dynamodb

Please let us know if it's still not clear enough.

**Comment by bostrowski13** [comment]
Sorry for the late follow up, was out on holiday last week.

Thank you for the additional documentation, was extremely helpful in the way that I think I get how this is supposed to be structured in dynamodb.  However, the question I had was if the config file for resolver (and enrichments) are supposed to be stored.  Is it expected that the entire resolver.json file (for example) is stored in the "json" column as a String?  or will additional formatting of that file be needed for using dynamodb?

At present, this is my config, which is attempting to insert the entire resolver.json file into the "json" column.  

```Terraform
resource "aws_dynamodb_table_item" "resolver_json" {
  table_name = aws_dynamodb_table.sp_enricher_config_table.id
  hash_key   = "id"
  item       = <<ITEM
  {
    "id": {"S": "resolver"},
    "json": {"S": "${data.template_file.resolver_json_tpl.rendered}"}
  }
  ITEM
}
```

If this is not what is expected, can you provide some more clarity?

**Comment by bostrowski13** [comment]
As an aside, why not use read from s3?  much easier to upload files to and read from.  

Also, is this related to what I'm asking?  https://github.com/snowplow/enrich/issues/126

**Comment by benjben** [comment]
>  Is it expected that the entire resolver.json file (for example) is stored in the "json" column as a String?

Yes the whole JSONs should be place in `json` column.

> As an aside, why not use read from s3? much easier to upload files to and read from.

That would require the same steps : put the config somewhere and then point to it at launch. Internally we run enrich with the Docker image  and we use `--resolver file:/snowplow/config/iglu_resolver.json --enrichments file:/snowplow/config/enrichments/` ([see](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/enrichment-components/stream-enrich/run-stream-enrich/#1-1-docker-image-recommended)).

We have just released a Terraform module that can help you to deploy Stream Enrich on EC2, you can find it [here](https://registry.terraform.io/modules/snowplow-devops/enrich-kinesis-ec2/aws/latest).

**Comment by bostrowski13** [comment]
I was able to work out a solution from the provided terraform repo.  This is excellent, thank you for this resource and your quick responses.
