### ISSUE TITLE
Common: loading S3 data within EKS needs STS

### ISSUE THREAD

**Issue by adamschmidt** [snowplow/enrich#482]
**Project**: Common

**Version**: 2.0.1

**Expected behavior**: starting the Enricher container on EKS should be able to load data from S3 on startup

**Actual behavior**: the container crashes with `An error occured: Attempt to download s3://<bucket>/<path>/GeoLite2-City.mmdb to ./ip_geo failed: No AWS credentials provided`

**Steps to reproduce**:

 1. Push enricher data files to S3 bucket
 2. Create IAM role and assign to EKS service account
 3. Assign EKS service account to containier
 4. Start container, watch for failure

It seems as though either an AWS SDK upgrade to the latest 2.x version or inclusion of AWS' STS library as a dependency might be the answer to this: https://github.com/aws/aws-sdk-java-v2/issues/1470

Workaround might be to use an init container and use the AWS CLI container to download artefacts from S3 on start and read locally, rather than sourcing from S3 directly within the Enricher container.

**Comment by chuwy** [comment]
Thanks for the report, @adamschmidt. We'll look at it.

We're working on an overhaul of Stream Enrich to make it use the same tech stack as [Enrich PubSub](https://discourse.snowplowanalytics.com/t/enrich-2-0-0-released/5105#features-of-snowplow-enrich-pubsub-1) and compatible configuration. And likely this change (with SDKv2) will be implemented there (cc @benjben)

**Comment by adamschmidt** [comment]
Perfect! Thanks @chuwy.

I think that the crux of the problem lies here or hereabouts: https://github.com/snowplow/enrich/blob/321dd29590e0c725595d9a7ec38e1ab45e9d1e0d/modules/stream/src/main/scala/com.snowplowanalytics.snowplow.enrich.stream/utils.scala#L74

We need the equivalent of:

```
...
                    case AWSCredentials(a, s) if isKiam(a) && isKiam(s) =>
                      return WebIdentityTokenCredentialsProvider.create().asRight
                    case AWSCredentials(a, s) if isKiam(a) || isKiam(s) =>
                      "accessKey and secretKey must both be set to 'kiam' or neither".asLeft
...
```

where:

```
def isKiam(key: String): Boolean = key == "kiam"
```

**Comment by adamschmidt** [comment]
Incidentally, tried an init container and it didn't work:

https://github.com/snowplow/enrich/blob/321dd29590e0c725595d9a7ec38e1ab45e9d1e0d/modules/stream/src/main/scala/com.snowplowanalytics.snowplow.enrich.stream/Enrich.scala#L261

The enricher config can't be loaded from a `file://` scheme URI. It only supports `s3://`, `http://`, `https://`, or `gs://`.

**Comment by chuwy** [comment]
Regardless of whether this will be part of Stream Enrich overhaul or class Stream Enrich, I think it's worth to add to 2.1.0 as we want to treat EKS seriously and from @adamschmidt seems to be easy to fix.

**Comment by benjben** [comment]
Duplicate with #318
