### ISSUE TITLE
common: Use schemas/nl.basjes/yauaa_context/jsonschema/1-0-3

### ISSUE THREAD

**Issue by istreeter** [snowplow/enrich#515]
I have seen the following message in a Snowplow failed event, relating to the yauaa context:

```
   {
     "message": "",
     "path": "$.agentVersionMajor",
     "keyword": "maxLength",
     "targets": [
       "20"
     ]
  }
```

I do not know the value that caused this violation.  We should investigate what is the maximum length of this field (and indeed other fields, if possible) and consider publishing a new revision of the schema.

**Comment by paulboocock** [comment]
We got this schema update contribution along similar lines: https://github.com/snowplow/iglu-central/issues/1126

**Comment by benjben** [comment]
This has been fixed [here](https://github.com/snowplow/iglu-central/commit/69b3e475a0fdf1226ae6d24dc34a157799bf7e76#diff-667daa5101dc3744da3224a46c0444975d764080bd404c21eb298d5ad18b2037R106).
