### ISSUE TITLE
Stream Enrich Kafka: bump Kafka Client to 2.8.1

### ISSUE THREAD

**Issue by Tronok** [snowplow/enrich#518]
**Project**:  Stream Enrich Kafka

**Version**: 2.0.2

**Expected behavior**: INVALID_FETCH_SESSION_EPOCH errors rarely happens/ 

**Actual behavior**: Stream enrich produces excessive amount of logs due to INVALID_FETCH_SESSION_EPOCH error. 

Currently Kafka client is pretty outdated for stream enrich. It causes degraded performance and this [error which was fixed](https://issues.apache.org/jira/browse/KAFKA-8052) in the later versions of Kafka client (starting from 2.3). Is there a plan to upgrade Kafka client? I made local build with version 2.8.1 and it works fine

**Comment by benjben** [comment]
Thanks @Tronok ! This will be included in Enrich 3.0.0 that will be released this month. It will be announced on [discourse](https://discourse.snowplowanalytics.com/).
