### ISSUE TITLE
common: catch and handle errors in the CurrencyConversionEnrichment

### ISSUE THREAD

**Issue by istreeter** [snowplow/enrich#542]
We have seen exceptions thrown by our forex library [on this line here](https://github.com/snowplow/enrich/blob/2.0.5/modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/CurrencyConversionEnrichment.scala#L124-L127).  They never get handled and properly converted to EnrichmentFailures.

If it happens in enrich-pubsub then it bubbles up and gets caught [here](https://github.com/snowplow/enrich/blob/2.0.5/modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/enrich/pubsub/Enrich.scala#L120-L132) and converted to a GenericError.

If it happens in stream-enrich then it bubbles up [to here](https://github.com/snowplow/enrich/blob/2.0.5/modules/stream/common/src/main/scala/com.snowplowanalytics.snowplow.enrich.stream/sources/Source.scala#L171-L179) where it gets logged in sentry but we do not generate a bad row, so there is data loss.

I think [this is the line in scala-forex](https://github.com/snowplow/scala-forex/blob/1.0.0/src/main/scala/com.snowplowanalytics/forex/OerClient.scala#L172) that throws the original exception.  It is a `NoSuchElementException` with message `key not found: AED`.  But for now that's not the point -- the point is Enrich should expect exceptions and handle them.

**Comment by benjben** [comment]
It's not possible to reproduce this in the unit tests as the root error lives in `scala-forex`

Related issue : https://github.com/snowplow/scala-forex/issues/179
