### ISSUE TITLE
enrich-kinesis: Fix disabling cloudwatch metrics

### ISSUE THREAD

**Issue by istreeter** [snowplow/enrich#580]
The enrich-kinesis config file allows a parameter `monitoring.metrics.cloudwatch`.  However, when we had it set to `false` we found that metrics got published to cloudwatch anyway.

**Comment by ibexmonj** [comment]
This is still happening on my end when using `snowplow-enrich-kinesis:3.1.2` .
I have tried removing the `monitoring` block from the config as well as setting cloudwatch to false explicitly and no matter what i do it seems to be attempting to send metrics to cloudwatch.

**Comment by istreeter** [comment]
Hi @ibexmonj please can you share the full config file you are using?  (removing any sensitive fields).  And any more details of which metrics you see appearing in cloudwatch?

I had not noticed any problem with this configuration option, but I'm happy to take a look.

**Comment by istreeter** [comment]
Oh, sorry about that documentation mistake.  I just fixed it to now say `monitoring.metrics.cloudwatch` [here](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/enrichment-components/enrich-pubsub/configuration-reference/#enrich-kinesis-1).

> Happy to help with documentation changes if someone can guide me.

This was a very kind offer!  Currently we don't have somewhere to accept open-source contributions for our docs, but this is something I hope will change in future.
