### ISSUE TITLE
enrich-kinesis: add STS v2 to runtime dependencies

### ISSUE THREAD

**Issue by svdimchenko** [snowplow/enrich#643]
**Project**: Snowplow Enrich Kinesis

**Version**: 3.1.5

**Expected behavior**: when deployed on EKS cluster enricher should be able to assume irsa role with corresponding permissions which are provided. Other snowplow components (collector, s3loader, rdbloader, iglu server) assume the role and work properly.

**Actual behavior**:
enricher assumes node group's role and get exception.
```
software.amazon.kinesis.leases.exceptions.DependencyException: software.amazon.awssdk.services.dynamodb.model.DynamoDbException: User: arn:aws:sts::<account-id>:assumed-role/snowplow-eks-node-group-<node-group-id>/<...> is not authorized to perform: dynamodb:CreateTable on resource: arn:aws:dynamodb:<region>:<account-id>:table/snowplow-enrich-app because no identity-based policy allows the dynamodb:CreateTable action (Service: DynamoDb, Status Code: 400, Request ID: <request_id>)
```

**Steps to reproduce**:
 1. Deploy image `snowplow/snowplow-enrich-kinesis:3.1.5` on kubernetes
 2. Ckeck container logs

**Comment by AurimasGr** [comment]
Hi, 

I've run into the same problem. The way AWS EKS IRSA works is that on assigning a service account to the pod a web identity token is created as a file in the pod and two environment variables are set: 

AWS_ROLE_ARN - the AWS IAM role arn of the role to be assumed by the pod.
AWS_WEB_IDENTITY_TOKEN_FILE - points to the web identity token to be used for authentication.

Default chain should take these env variables as the top priority if I am not mistaken.

Btw, as mentioned - scala stream collectors work fine.

**Comment by svdimchenko** [comment]
@benjben for now I've resolved the issue by adding required role on node group level in my EKS cluster. However it's much more secure way to use [irsa](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) instead.

**Comment by hanfi** [comment]
any update on this issue i'm facing the same problem,

it's wierd because it works for the kinesis client : it uses the IRSA

but for dynamoDB client it uses the instance Role of the node 

i'm searching for a solution but since my lvl of scala is minus 50000 i'm struggling building, understanding and debuging

the enrich project
