### ISSUE TITLE
Add enrich-kafka

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/enrich#648]
Following the enrich-kinesis and enrich-pubsub projects, we'll have a new app for Kafka to be able to deprecate `stream-enrich-kafka`

**Comment by shadiramadan** [comment]
Oh I was about to ask when this kafka support is coming and you committed 26 min ago!  Thanks for working on this!

**Comment by blu3gui7ar** [comment]
Looking forward for the release.

**Comment by oguzhanunlu** [comment]
Hi @shadiramadan @blu3gui7ar , we released enrich-kafka today! I hope you're still interested in the project. Any feedback and comment are much appreciated!
