### ISSUE TITLE
enrich-kinesis: Checkpoint only fully processed records

### ISSUE THREAD

**Issue by istreeter** [snowplow/enrich#652]
Currently, [enrich-kinesis calls](https://github.com/snowplow/enrich/blob/3.2.0/modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/enrich/kinesis/KinesisRun.scala#L76) `record.checkpointer.checkpoint` after a batch of events has been fully processed.  Under the hood this calls the `checkpoint` method on [the RecordProcessCheckpointer](https://javadoc.io/static/software.amazon.kinesis/amazon-kinesis-client/2.2.6/software/amazon/kinesis/processor/RecordProcessorCheckpointer.html) which is described as:

> This method will checkpoint the progress at the last data record that was delivered to the record processor.

But this is not the right method to call!  Because the "last data record that was delivered to the record processor" is not the same as the last record that has been safely written out to Kinesis.  Instead, we need to call simply `record.checkpoint`, which [under the hood](https://github.com/laserdisc-io/fs2-aws/blob/v3.1.1/fs2-aws/src/main/scala/fs2/aws/kinesis/CommittableRecord.scala#L34) handles checkpointing of the precise record that has been processed.

Without a fix, there is potential data loss as we checkpoint records that have not been processed.

**Comment by benjben** [comment]
:scream: good catch !
