### ISSUE TITLE
Enrich-kinesis: recover from IllegalArgumentException when checkpointing near end of shard

### ISSUE THREAD

**Issue by istreeter** [snowplow/enrich#657]
A pipeline raised this exception upon checkpointing:

```
java.lang.IllegalArgumentException: Could not checkpoint at extended sequence number {SequenceNumber: 49631577401484660731866404223772970925544731690085361266,SubsequenceNumber: 0} as it did not fall into acceptable range between the last checkpoint {SequenceNumber: SHARD_END,SubsequenceNumber: 0} and the greatest extended sequence number passed to this record processor {SequenceNumber: SHARD_END,SubsequenceNumber: 0}
```

The exception itself comes [from here in amazon-kinesis-client](https://github.com/awslabs/amazon-kinesis-client/blob/a344ee4d05d19d4786a7a4d5d5062adcc080a8c0/amazon-kinesis-client/src/main/java/software/amazon/kinesis/checkpoint/ShardRecordProcessorCheckpointer.java#L124-L129).  But it's very hard to work out exactly how we got into this inconsistent state.

The exception happened when enrich reached the end of a shard, and as it started to process the child shards.  Enrich is supposed to call the checkpointer twice when this happens:

1. First checkpoint the last record in the shard, which [we do explicitly here](https://github.com/snowplow/enrich/blob/3.2.2/modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/enrich/kinesis/KinesisRun.scala#L85)
2. Then checkpoint the shard end.  This is handled for us by fs2-aws by clever use of a semaphore, [here](https://github.com/laserdisc-io/fs2-aws/blob/v3.1.1/fs2-aws/src/main/scala/fs2/aws/kinesis/CommittableRecord.scala#L35) and [here](https://github.com/laserdisc-io/fs2-aws/blob/v3.1.1/fs2-aws/src/main/scala/fs2/aws/kinesis/ChunkedRecordProcessor.scala#L37-L38).

The exception happens on point 1.  For some reason, by the time we try to checkpoint the last record in the shard, the internal state of KCL has been updated only allow checkpointing of the shard end.  I just cannot figure out how this happens, but it might be related to KCL starting to process the child shards already; and because we have quite a long gap between reading the last record in the shard and checkpointing it.

The app restarted and crashed again with the same error again.  This makes me confident that we had not accidentally checkpointed the last record in the shard before we were ready.  i.e. it's only the internal state of KCL that is wrong; there is no deeper problem with checkpointing.

My proposed solution is to catch the `IllegalArgumentException` in [this recoverWith block](https://github.com/laserdisc-io/fs2-aws/blob/v3.1.1/fs2-aws/src/main/scala/fs2/aws/kinesis/ChunkedRecordProcessor.scala#L37-L38).  But instead of ignoring the error completely, we also need to release the semaphore, so that aws-fs2 checkpoints the shard end (point 2 on list above).

**Comment by benjben** [comment]
I agree with your interpretation and your proposed solution.

From what I understand from these log lines:
```
1658363429509,[ShardRecordProcessor-0015] INFO software.amazon.kinesis.lifecycle.ProcessTask - Reached end of shard shardId-000000014951 and have no records to process
1658363430419,[ShardRecordProcessor-0015] INFO software.amazon.kinesis.lifecycle.ShutdownTask - Shard shardId-000000014951: Created child shard lease: shardId-000000014957
1658363430432,[ShardRecordProcessor-0015] INFO software.amazon.kinesis.lifecycle.ShutdownTask - Shard shardId-000000014951: Created child shard lease: shardId-000000014958
1658363430438,"[ShardRecordProcessor-0015] INFO software.amazon.kinesis.lifecycle.ShutdownTask - Shard shardId-000000014951: Updated current lease shardId-000000014951 with child shard information: [shardId-000000014958, shardId-000000014957]"
```
the shard `shardId-000000014951` has been [splitted](https://docs.aws.amazon.com/streams/latest/dev/kinesis-using-sdk-java-resharding-split.html) into shard `shardId-000000014957` and shard  `shardId-000000014958`.

Then we can see:
```
1658363431005,"[prefetch-cache-shardId-000000014951-0000] ERROR software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher - snowplow-au-com-catch-prod1-collector-payloads:shardId-000000014951 :  Unexpected exception was thrown. This could probably be an issue or a bug. Please search for the exception/error online to check what is going on. If the issue persists or is a recurring problem, feel free to open an issue on, https://github.com/awslabs/amazon-kinesis-client."
1658363431005,"java.lang.IllegalStateException: Shutdown has been called on the cache, can't accept new requests."
```
It kind of looks like KCL tries to prefetch records on a shard that doesn't exist any more (due to the split).

@jbeemster is it the case that Tupilak splits shards?

**Comment by istreeter** [comment]
Since you mention this exception, and I had forgot to mention it:

> java.lang.IllegalStateException: Shutdown has been called on the cache

I figured out where this exception comes from in KCL ([here](https://github.com/awslabs/amazon-kinesis-client/blob/v2.4.1/amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/polling/PrefetchRecordsPublisher.java#L283)), and I think it's not directly linked to the later exceptions about checkpointing.  Both exceptions happen because a parent shard splits into two children; but it is not the case that one exception causes the other exception.  And from the code I'm fairly sure the KCL happily recovers from the first exception about the prefetch cache.  It logs the error and moves on.
