### ISSUE TITLE
Stream Enrich: Fix the enrichment order

### ISSUE THREAD

**Issue by spenes** [snowplow/enrich#662]
In version [3.2.0](https://github.com/snowplow/enrich/releases/tag/3.2.0), we've made change on the enrichment order. Details can be found [here](https://github.com/snowplow/enrich/issues/619).

The original problem was only on the enrich-kinesis and enrich-pubsub. Enrichment order on the stream-enrich was correct. During this change, we've introduced [legacyEnrichmentOrder](https://github.com/snowplow/enrich/blob/5d9e6ef71feabd5e46c1b202aa181178d33d595a/modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/EtlPipeline.scala#L45) flag to fix order in enrich-kinesis and enrich-pubsub without making this breaking change. `legacyEnrichmentOrder = true` means preserve the wrong order used in the enrich-kinesis and enrich-pubsub.

The problem is we've set [legacyEnrichmentOrder to true](https://github.com/snowplow/enrich/blob/master/modules/stream/common/src/main/scala/com.snowplowanalytics.snowplow.enrich.stream/sources/Source.scala#L163) in the stream-enrich as well this means using the wrong enrichment order instead of correct one in the stream-enrich. We've should make it `false`.

**Comment by istreeter** [comment]
For reference, I will document here the correct enrichment order, and the mistaken enrichment order.

**Correct order**

- IAB
- User agent utils
- UA parser
- Currency converter
- Referer parser
- Campaign attribution
- Event fingerprint
- Cookie extractor
- Http header extracter
- Weather
- Yauaa
- IP Lookups
- Javascript
- SQL
- API request
- IP anonymisation
- PII psudonymisation

**Incorrect order**

- IAB
- User agent utils
- UA parser
- Referer parser
- Campaign attribution
- Event fingerprint
- Cookie extractor
- Http header extracter
- Yauaa
- Javascript
- Currency converter
- Weather
- IP Lookups
- SQL
- API request
- IP anonymisation
- PII psudonymisation
